etalab/formulaire-qf

config/settings/production.yml
=> Sandbox is iso production for config logic

app/controllers/shipments_controller.rb, app/interactors/create_shipment.rb, app/models/shipment.rb, app/views/shipments/show.html.erb, config/locales/fr.yml, config/routes.rb, db/migrate/20240626085723_add_reference_and_hubee_status_to_shipments.rb, db/schema.rb, features/step_definitions/web_steps.rb, features/transmettre_mes_informations.feature, spec/models/shipment_spec.rb
Ainsi qu'une colonne de suivi du statut HubEE.
:warning: A merger après #38
=> Ajoute une référence de demande à destination des usagers 

config/locales/fr.yml, features/accueil.feature, features/france_connexion.feature, features/sélectionner_une_commune.feature, features/transmettre_mes_informations.feature
Restructuration générale des wordings
Passage des titres pirncipaux et de la taglin au singulier.
Pour mettre plus en avant que c'est une démarche grand public, comme le fais service public ici : https://www.service-public.fr/particuliers/vosdroits/comment-faire-si
=> Change formulation page choix de la collectivité

Gemfile
=> Charge factory_bot dans tous les envs

app/views/layouts/_analytics.html.erb, app/views/layouts/application.html.erb
Closes https://linear.app/pole-api/issue/API-2967/installer-matomo-et-verifier-que-le-parcours-est-bien-tracke-jusquau
=> add matomo

app/controllers/collectivities_controller.rb, app/controllers/sessions_controller.rb, config/routes.rb, features/step_definitions/web_steps.rb
Closes https://linear.app/pole-api/issue/API-2998/changer-les-termes-dans-lurl
=> Improve urls

app/facades/quotient_familial_facade.rb, app/models/shipment_data.rb, app/views/shipments/new.html.erb, config/locales/fr.yml, features/transmettre_mes_informations.feature, spec/factories/quotient_familial_payload.rb, spec/models/shipment_data_spec.rb
Closes https://linear.app/pole-api/issue/API-3009/afficher-correctement-les-qf-avec-donnees-manquantes-regime-month-year
=> Améliore la gestion des erreurs QF et données manquantes

Gemfile, Gemfile.lock, app/controllers/sessions_controller.rb, app/controllers/shipments_controller.rb, app/facades/pivot_identity_facade.rb, app/facades/quotient_familial_facade.rb, app/interactors/get_family_quotient.rb, app/models/shipment_data.rb, app/views/collectivities/_alternatives.html.erb, app/views/collectivities/no_france_connect.html.erb, app/views/layouts/_flash.html.erb, app/views/layouts/application.html.erb, app/views/shipments/error.html.erb, app/views/shipments/new.html.erb, config/locales/fr.yml, config/routes.rb, features/france_connexion.feature, features/transmettre_mes_informations.feature, lib/api_particulier/quotient_familial_v2.rb, spec/facades/pivot_identity_facade_spec.rb, spec/facades/quotient_familial_facade_spec.rb, spec/factories/pivot_identities.rb, spec/interactors/get_family_quotient_spec.rb, spec/lib/api_particulier/quotient_familial_v2_spec.rb, spec/models/pivot_identity_spec.rb, spec/models/shipment_data_spec.rb, spec/support/provider_stubs/api_particulier.rb
Closes https://linear.app/pole-api/issue/API-2924/gerer-les-cas-derreurs
=> Improve error management

app/views/layouts/_header.html.erb, app/views/layouts/_skiplinks.html.erb, app/views/layouts/application.html.erb
Closes https://linear.app/pole-api/issue/API-2996/ajouter-le-composant-lien-devitement-or-accessibilite
=> add skiplinks for accessibility

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/facades/quotient_familial_facade.rb, app/models/shipment_data.rb, app/views/collectivities/_alternatives.html.erb, app/views/collectivities/_show_banner.html.erb, app/views/collectivities/index.html.erb, app/views/collectivities/no_france_connect.html.erb, app/views/collectivities/show.html.erb, app/views/home/_cta.html.erb, app/views/home/faq.html.erb, app/views/home/index.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, app/views/shipments/new.html.erb, app/views/shipments/show.html.erb, config/locales/fr.yml, features/static_pages.feature, spec/lib/api_particulier/quotient_familial_v2_spec.rb
Closes https://linear.app/pole-api/issue/API-2997/ajouter-un-titre-par-onglet-de-chaque-page-or-accessibilite
=> Page tab titles

app/interactors/create_shipment.rb, app/interactors/prepare_quotient_familial_hubee_folder.rb, app/models/shipment.rb, db/migrate/20240703140539_add_uniqueness_to_shipments_reference.rb, db/schema.rb, spec/factories/shipments.rb, spec/interactors/create_shipment_spec.rb, spec/interactors/prepare_quotient_familial_hubee_folder_spec.rb, spec/models/shipment_spec.rb
Closes https://linear.app/pole-api/issue/API-3090/verifier-quune-reference-generee-nexiste-pas-deja
=> no duplicated references

app/assets/stylesheets/application.css.erb, app/views/home/faq.html.erb, app/views/shipments/show.html.erb, config/locales/fr.yml, features/accueil.feature, features/france_connexion.feature, features/step_definitions/web_steps.rb, features/sélectionner_une_commune.feature, features/transmettre_mes_informations.feature
Closes https://linear.app/pole-api/issue/API-2396/mettre-le-bouton-je-donne-mon-avis
=> add feedback button

app/controllers/shipments_controller.rb, app/interactors/prepare_quotient_familial_hubee_folder.rb, app/jobs/populate_hubee_sandbox_job.rb, app/models/collectivity.rb, app/models/shipment.rb, db/migrate/20240704131031_add_collectivity_id_to_shipments.rb, db/schema.rb, spec/factories/shipments.rb, spec/interactors/create_shipment_spec.rb, spec/interactors/prepare_quotient_familial_hubee_folder_spec.rb, spec/jobs/populate_hubee_sandbox_job_spec.rb, spec/organizers/store_quotient_familial_spec.rb, spec/organizers/upload_quotient_familial_to_hubee_spec.rb
Closes https://linear.app/pole-api/issue/API-3123/link-shipments-and-collectivities-in-db
=> Link shipments and collectivities for stats and debug

app/jobs/populate_hubee_sandbox_job.rb, features/step_definitions/mock_steps.rb, spec/facades/quotient_familial_facade_spec.rb, spec/factories/france_connect_payload.rb, spec/factories/quotient_familial_payload.rb, spec/interactors/get_family_quotient_spec.rb, spec/interactors/prepare_quotient_familial_hubee_folder_spec.rb, spec/lib/api_particulier/quotient_familial_v2_spec.rb, spec/models/shipment_data_spec.rb, spec/organizers/store_quotient_familial_spec.rb, spec/organizers/upload_quotient_familial_to_hubee_spec.rb, spec/support/provider_stubs/api_particulier.rb
Closes https://linear.app/pole-api/issue/API-3026/utiliser-les-factories-de-quotient-familial-payload-dans
=> Improve factory of quotient familial payload

app/controllers/sessions_controller.rb, app/controllers/shipments_controller.rb, app/interactors/hubee/create_folder.rb, app/models/shipment_data.rb, config/locales/fr.yml, features/step_definitions/mock_steps.rb, features/transmettre_mes_informations.feature, lib/hubee/api.rb, lib/hubee/api/response.rb, spec/interactors/hubee/create_folder_spec.rb, spec/lib/hubee/api/response_spec.rb, spec/lib/hubee/api_spec.rb, spec/support/provider_stubs/hubee.rb
Closes https://linear.app/pole-api/issue/API-3179/debug-hubee-api
=> Debug hubee api

config/initializers/good_job.rb
Sur les coneils de Sébastien, éviter les "heures pile"
=> request hebee on the 10th min of the hour

.github/workflows/specs.yml
Closes https://linear.app/pole-api/issue/API-3286/deploiement-automatique-sur-main
=> continuous deployment on main

app/views/layouts/application.html.erb, app/views/shared/_support_banner.html.erb
Closes https://linear.app/pole-api/issue/API-3214/bandeau-de-support
=> add support banner

.github/workflows/specs.yml
cf https://github.com/etalab/siade/pull/1393
=> Exécute le CI uniquement sur les PR ouvertes avec une review requise

app/controllers/api/collectivities_controller.rb, app/models/collectivity.rb, db/migrate/20241003132344_add_not_null_constraint_to_departement.rb, db/schema.rb, spec/models/collectivity_spec.rb
=> Rend le département obligatoire sur une collectivité

lib/api_particulier/quotient_familial/v2.rb
This reverts commit 9350e00bb96410e1dca6245bf65a8dbf72817798.
=> Revert "fake user token for staging"

app/organizers/datapass_webhook/setup_collectivity.rb
Résout https://errors.data.gouv.fr/organizations/sentry/issues/248677/?project=29&query=is%3Aunresolved&referrer=issue-stream
=> Fixe le setup de collectivité sans service_provider

README.md, app/controllers/api/collectivities_controller.rb, config/routes.rb, spec/controllers/api/collectivities_controller_spec.rb
Closes https://linear.app/pole-api/issue/API-4358/ajouter-un-endpoint-pour-collectivitesfr
=> add api endpoint collectivity#show

app/facades/quotient_familial_facade.rb, app/interactors/get_family_quotient.rb, app/models/pivot_identity.rb, app/models/shipment_data.rb, features/api_errors.feature, lib/api_particulier/quotient_familial/base.rb, lib/api_particulier/quotient_familial/v1.rb, lib/api_particulier/quotient_familial/v1_payload.rb, lib/api_particulier/quotient_familial/v2.rb, spec/facades/quotient_familial_facade_spec.rb, spec/factories/quotient_familial_payload.rb, spec/interactors/get_cnaf_v1_family_quotient_spec.rb, spec/interactors/get_family_quotient_spec.rb, spec/lib/api_particulier/quotient_familial/v1_payload_spec.rb, spec/lib/api_particulier/quotient_familial/v2_spec.rb, spec/models/shipment_data_spec.rb, spec/support/provider_stubs/api_particulier.rb
This PR focusses on updating the request for QFv2 to API PART V3.
Some unification and additionnal tests have been added to make sure everything works fine
=> Migrating QFv2 to API PART V3

app/assets/stylesheets/application.css.erb, app/controllers/application_controller.rb, app/views/collectivities/_alternatives.html.erb, app/views/home/faq.html.erb, app/views/layouts/_footer.html.erb, config/locales/fr.yml
Fix accessibility problems described in https://ara.numerique.gouv.fr/rapport/_xnJplI5antrSGyjJohlU/details-des-non-conformites
=> Accesibilite : 2eme vague de corrections
